[project]
name = "pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rohit Tinker", email = "110806091+rohittinker@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.4.2",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=25.0.0",
    "sqlalchemy>=2.0.51",
]

[project.scripts]
pipeline = "pipeline:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pgcli>=4.5.0",
]
